import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const DOC_CACHE_TTL_MS = 24 * 60 * 60 * 1000;
const DOCS_INDEX_PATH = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'data', 'apidocs.txt');
const DOCS_BASE_URL = 'https://developers.zuper.co/reference/';

// Matches lines like `- [Title](https://developers.zuper.co/reference/create-job.md): description`
// from the llms.txt-style index — see src/mastra/data/apidocs.txt.
const INDEX_LINE = /^-\s*\[([^\]]+)\]\(([^)]+)\)(?::\s*(.*))?$/;

interface DocIndexEntry {
  title: string;
  slug: string;
  description: string;
}

function normalize(value: string): string {
  return value.trim().toLowerCase();
}

function parseIndex(raw: string): DocIndexEntry[] {
  const entries: DocIndexEntry[] = [];
  for (const line of raw.split('\n')) {
    const match = INDEX_LINE.exec(line.trim());
    if (!match) continue;
    const [, title, url, description] = match;
    if (!url) continue;
    // Only the "## API Reference" rows resolve to an endpoint doc — Guides/Changelog entries use
    // /docs/ and /changelog/ paths and aren't relevant to a workflow node's action.
    const marker = '/reference/';
    const markerIndex = url.indexOf(marker);
    if (markerIndex === -1) continue;
    const slug = url.slice(markerIndex + marker.length);
    if (!slug) continue;
    entries.push({ title: title ?? '', slug, description: description ?? '' });
  }
  return entries;
}

let indexPromise: Promise<DocIndexEntry[]> | null = null;

function loadIndex(): Promise<DocIndexEntry[]> {
  if (!indexPromise) {
    indexPromise = readFile(DOCS_INDEX_PATH, 'utf8').then(parseIndex).catch(() => []);
  }
  return indexPromise;
}

// Slugs are not reliably derivable from a title (legacy/autogenerated slugs like `create-job-copy.md`
// exist in the real index), so entries are matched by title text, not computed.
async function findEntry(actionName: string): Promise<DocIndexEntry | null> {
  const entries = await loadIndex();
  const normalized = normalize(actionName);
  if (!normalized) return null;
  return (
    entries.find((e) => normalize(e.title) === normalized) ??
    entries.find((e) => normalize(e.title).includes(normalized) || normalized.includes(normalize(e.title))) ??
    null
  );
}

interface CacheEntry {
  promise: Promise<string>;
  fetchedAt: number;
}

const docCache = new Map<string, CacheEntry>();

async function fetchDocPage(slug: string): Promise<string> {
  const res = await fetch(`${DOCS_BASE_URL}${slug}`);
  if (!res.ok) throw new Error(`DOCS_${res.status}`);
  return res.text();
}

/** Resolves a node's action name to its Zuper API reference page and fetches that one page's real
 * markdown content, live, on demand — never the whole ~450-entry index. Docs change rarely, so the
 * cache TTL is long. Returns null when no matching endpoint doc exists, rather than guessing. */
export async function getEndpointDoc(actionName: string, forceRefresh = false): Promise<string | null> {
  const entry = await findEntry(actionName);
  if (!entry) return null;

  const cached = docCache.get(entry.slug);
  const stale = !cached || Date.now() - cached.fetchedAt > DOC_CACHE_TTL_MS;
  if (!cached || stale || forceRefresh) {
    docCache.set(entry.slug, { promise: fetchDocPage(entry.slug), fetchedAt: Date.now() });
  }

  try {
    return await docCache.get(entry.slug)!.promise;
  } catch {
    docCache.delete(entry.slug);
    return null;
  }
}
